version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    cyclop:
      max-complexity: 14
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 90
      statements: 60
    godox:
      keywords:
        - OPTIMIZE
    lll:
      line-length: 128
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: var-naming
          arguments:
            - - ID
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test\.go
      - path: (.+)\.go$
        text: exported (const|var|type|method|function) (.+) should have comment (.+) or be unexported
      - path: (.+)\.go$
        text: exported (const|var|type|method|function) (.+) should have comment or be unexported
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/HewlettPackard
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
